destinationnode:
  grpcport: 9090
  ip: 127.0.0.1
  port: 26657
  protocol: tcp
  chainid: fairyring_devnet
  accountprefix: fairy

fairyringnode:
  grpcport: 9090
  ip: 127.0.0.1
  port: 26657
  protocol: tcp
  chainid: fairyring_devnet
  accountprefix: fairy

derivepath: m/44'/118'/0'/0/0
mnemonic: 'record gift you once hip style during joke field prize dust unique length more pencil transfer quit train device arrive energy sort steak upset'